spring:
  application:
    name: worldchat
  jpa:
    hibernate:
      ddl-auto: update #TODO: change to validate
  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/worldchat

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

server:
  servlet:
    session:
      timeout: 30m

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web: TRACE
    org.springframework.security.config: TRACE

